# TODO: enable again
trigger:
    batch: true
    branches:
        include:
            - 'v3'

variables:
    # Make sure we're exiting training as early as possible
    SPACY_CONFIG_OVERRIDES: '--training.max_epochs=1 --training.max_steps=1'
    WASABI_LOG_FRIENDLY: 1

jobs:
    - job: 'Test'
      strategy:
          matrix:
              Python37Linux:
                  imageName: 'ubuntu-16.04'
                  python.version: '3.7'
              Python37Windows:
                  imageName: 'vs2017-win2016'
                  python.version: '3.7'
          maxParallel: 4
      pool:
          vmImage: $(imageName)

      steps:
          - task: UsePythonVersion@0
            inputs:
                versionSpec: '$(python.version)'
                architecture: 'x64'

          - script: |
                pip install "spacy>=3.0.1,<3.1.0"
                pip install pytest
                pip install "numpy<1.20.0"
                pip install torch==1.8.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            displayName: 'Install dependencies'

          - script: python -m pytest -s benchmarks experimental integrations pipelines tutorials
            displayName: 'Run tests'
