# GitHub Action that builds docs regularly

name: Build Docs
on:
  workflow_dispatch:  # allow manual trigger
  schedule:
    - cron: '0 8 * * 5'  # every Friday at 8am UTC

jobs:
  autodoc:
    if: github.repository_owner == 'explosion'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
      - name: Auto-format code if needed
        run: |
          python .github/update_docs.py
          python .github/update_category_docs.py
          python .github/update_projects_json.py
      - name: Check for modified files
        id: git-check
        run: echo modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
            title: Automated build of docs
            labels: meta
            commit-message: Automated docs build 
            committer: GitHub <noreply@github.com>
            author: explosion-bot <explosion-bot@users.noreply.github.com>
            body: _This PR is auto-generated._
            branch: docs-build
            delete-branch: true
            draft: false
      - name: Check outputs
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
